API_VERSION: 102
exp_name: clip_finetune_human_${API_VERSION}

DEBUG: false


K: 5
BATCH_SIZE: 32

EPOCHS: 10
WARMUP_EPOCH: 0

HUMAN_IN_THE_LOOP: true
THRESHOLD: 0.5
UPDATE_SIZE: 100


catalog:
  trial_result: result/${exp_name}_trial_result.csv
  trials_dataframe: result/${exp_name}_trials_dataframe.csv
  dataset_path: data/clip_dataset_${HUMAN_IN_THE_LOOP}_${DEBUG}

optuna:
  study_name: ${exp_name}
  storage: "sqlite:///result/${exp_name}.db"
  # load_if_exists: false
  skip_if_exists: true
  n_trials: 10