API_VERSION: 102
exp_name: clip_finetune_human_${API_VERSION}
USE_PUBLIC_DATASET: false 

DEBUG: false
MODEL_NAME: ViT-B/16
K: 5
BATCH_SIZE: 64
EVAL_BATCH_SIZE: 256 # for evaluation step with no_grad
PREP_BATCH_SIZE: 256 # for data preprocessing

EPOCHS: 5
WARMUP_EPOCH: 0

HUMAN_IN_THE_LOOP: true
THRESHOLD: 0.8
UPDATE_SIZE: 500

catalog:
  trial_result: result/${exp_name}_trial_result.csv
  trials_dataframe: result/${exp_name}_trials_dataframe.csv
  dataset_path: data/clip_dataset


optuna:
  study_name: ${exp_name}
  # storage: "sqlite:///result/${exp_name}.db"
  load_if_exists: true
  n_trials: 1